print ("========== PILIH MENU ==========")
print ("1. Tambah")
print ("2. Kurang")
print ("3. Kali")
print ("4. Bagi")
billpertama = int(input("Masukkan angka pertama:"))
billkedua = int(input("Masukkan angka kedua :"))
print ("Pilihan Anda: 1")
print ("hasil", billpertama+billkedua)


print ("========== PILIH MENU ==========")
print ("1. Tambah")
print ("2. Kurang")
print ("3. Kali")
print ("4. Bagi")
billpertama = int(input("Masukkan angka pertama:"))
billkedua = int(input("Masukkan angka kedua :"))
print ("Pilihan Anda: 2")
print ("hasil", billpertama-billkedua)

print ("========== PILIH MENU ==========")
print ("1. Tambah")
print ("2. Kurang")
print ("3. Kali")
print ("4. Bagi")
billpertama = int(input("Masukkan angka pertama:"))
billkedua = int(input("Masukkan angka kedua :"))
print ("Pilihan Anda: 3")
print ("hasil", billpertama*billkedua)

print ("========== PILIH MENU ==========")
print ("1. Tambah")
print ("2. Kurang")
print ("3. Kali")
print ("4. Bagi")
billpertama = int(input("Masukkan angka pertama:"))
billkedua = int(input("Masukkan angka kedua :"))
print ("Pilihan Anda: 4")
print ("hasil", billpertama/billkedua)

